name: simple_durations
description: "Int extensions to easily create a Duration"
version: 1.0.0
repository: https://github.com/johnbmangold/easy_durations
issue_tracker: https://github.com/johnbmangold/easy_durations/issues

environment:
  sdk: ^3.8.0


dev_dependencies:
  flutter_lints: ^6.0.0
  test: ^1.25.15
