name: simple_durations
description: "Int extensions to easily create a Duration"
version: 1.0.1
repository: https://github.com/johnbmangold/easy_durations
issue_tracker: https://github.com/johnbmangold/easy_durations/issues

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  test: ^1.25.15
  very_good_analysis: ^9.0.0
